import "server-only";

import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { SESSION_RE } from "@/components/activity/shared";
import { HISTORY_DIR } from "./activity";
import { resolveDbDir } from "./db/pglite";
import { BASE_PATH } from "./base-path";
import { PROJECT_ROOT } from "./project-root";
import { isDefaultRemote, type RemoteConfig } from "./remote-config";
import { localSourceConfig, LOCAL_INDEX_FILE, readRemoteConfig, readSourceSelection, remoteIndexFile, REMOTE_CACHE_DIR, REMOTE_INDEX_FILE, SOURCE_CONFIG_FILE, SOURCE_SETTINGS_FILE } from "./sources";

export interface StorageLocation {
  id: string;
  label: string;
  path: string;
  description: string;
  kind: "file" | "directory";
  exists: boolean;
  editable: boolean;
}

export function storageLocations(session: string): StorageLocation[] {
  if (!SESSION_RE.test(session)) throw new Error("Bad session id.");
  let remote: RemoteConfig | null = null;
  try { remote = readRemoteConfig(); } catch { /* Keep repair controls available. */ }
  const locations: Omit<StorageLocation, "exists">[] = [
    { id: "session", label: "This tab's activity file", path: path.join(HISTORY_DIR, session, "innernet.jsonl"), kind: "file", editable: true,
      description: "One JSON object per line. Edit or remove lines in a text editor, then reload History. Keep the at, app and kind fields. Other apps may have their own files beside this one." },
    { id: "history", label: "All activity and sessions", path: HISTORY_DIR, kind: "directory", editable: false,
      description: "Each session is a folder. Open one to find its activity files. Changes are picked up the next time you open History." },
    { id: "local-index", label: "Generated local pages", path: LOCAL_INDEX_FILE, kind: "file", editable: false,
      description: "Search and Innerpedia render pages from this JSON index. There is no separate HTML file per page. Edit your source folders, then sync; a sync replaces this file." },
    { id: "remote-index", label: "Generated GitHub pages", path: remote ? remoteIndexFile(remote) : path.dirname(REMOTE_INDEX_FILE), kind: remote ? "file" : "directory", editable: false,
      description: remote ? `A local snapshot of ${remote.owner}'s ${remote.repositories.length ? "selected" : "public"} GitHub repositories. Each saved account and repository list has its own snapshot.${isDefaultRemote(remote) ? " Before your first sync, the included quirq-ai snapshot is used." : " Sync Remote to generate these pages."}` : "GitHub snapshots are in this folder. Repair the saved GitHub configuration to find the active snapshot." },
    { id: "selection", label: "Your source choices", path: SOURCE_SETTINGS_FILE, kind: "file", editable: true,
      description: "Your Local and Remote choices, GitHub account and repository list. These settings are shared by this Innernet installation and survive restarts." },
    { id: "config", label: "Local folder configuration", path: SOURCE_CONFIG_FILE, kind: "file", editable: true,
      description: "Edit roots and maxDepth to choose folders and crawl depth. INNERNET_ROOTS and INNERNET_MAX_DEPTH, when set on the server, override this file." },
    { id: "database", label: "Database copy", path: resolveDbDir(), kind: "directory", editable: false,
      description: process.env.INNERNET_DB?.toLowerCase() === "off" ? "The database is currently off. The app is using its JSON and activity files." : "PGlite keeps a copy of the local index and activity here. Edit the activity files rather than database internals; use db:store and db:load to store or restore copies." },
    { id: "remote-cache", label: "GitHub download cache", path: REMOTE_CACHE_DIR, kind: "directory", editable: false,
      description: "Public repository clones used during remote sync. Downloaded copies may be replaced on the next sync; make lasting changes in the original repositories." },
    { id: "app-cache", label: "App build cache", path: path.join(PROJECT_ROOT, process.env.INNERNET_DIST_DIR || process.env.QUIRQ_DIST_DIR || ".next"), kind: "directory", editable: false,
      description: "Compiled app files, development traces and caches. These are regenerated by Next.js, independently of your source index and activity." },
    { id: "app", label: "App files", path: PROJECT_ROOT, kind: "directory", editable: false,
      description: "Innernet's source code, styles, bundled images, guide media and installed dependencies. Your indexed folders stay in their original locations above." },
  ];
  return locations.map((item) => ({ ...item, exists: fs.existsSync(item.path) }));
}

export function sourceInfo(session: string) {
  let remote: RemoteConfig | null = null;
  try { remote = readRemoteConfig(); } catch { /* The form can save a repaired configuration. */ }
  const indexPath = remote ? remoteIndexFile(remote) : "";
  let generatedAt: string | null = null;
  try { generatedAt = JSON.parse(fs.readFileSync(indexPath, "utf8")).meta.generatedAt ?? null; } catch { /* no snapshot yet */ }
  let local: { roots: string[]; maxDepth: number | null; error?: string };
  try {
    local = localSourceConfig();
  } catch {
    local = { roots: [], maxDepth: null, error: "Local folder configuration could not be read. Open its file below to fix the roots and maxDepth, then reload Sources. Remote is still available." };
  }
  return {
    selection: readSourceSelection(),
    local,
    remote: {
      ...(remote ?? { owner: "", repositories: [] }),
      label: remote ? `${remote.owner} ${remote.repositories.length ? "selected" : "public"} repositories` : "GitHub configuration needs attention",
      url: remote ? `https://github.com/${remote.owner}` : "https://github.com",
      indexPath, generatedAt, needsSync: !generatedAt,
      ...(!remote ? { error: "Saved GitHub settings are invalid. Enter the account and repositories below and save, or edit the source choices file to repair them." } : {}),
    },
    storage: storageLocations(session),
    browserStorage: [
      { label: "This tab", location: "sessionStorage: innernet-session, innernet-trail", description: `Your session ID and back/forward trail live in this browser tab. Inspect them in browser developer tools under Application > Session storage${BASE_PATH ? ` for this site's origin` : ""}. Activity itself is in the file above.` },
      { label: "Appearance", location: "localStorage: innernet-theme", description: "Your light/dark preference stays in this browser. Inspect it under Application > Local storage in browser developer tools." },
    ],
  };
}

/** Only named app locations may be opened, never a caller-supplied path or command. */
export async function openStorageLocation(session: string, target: string, action: "reveal" | "edit"): Promise<void> {
  const item = storageLocations(session).find((entry) => entry.id === target);
  if (!item) throw new Error("Unknown storage location.");
  if (action === "edit" && (!item.editable || item.kind !== "file" || !item.exists)) throw new Error("This file is not available to edit. Open its folder instead.");
  if (target === "session" && item.exists) {
    const root = fs.realpathSync(HISTORY_DIR);
    const file = fs.realpathSync(item.path);
    if (!file.startsWith(root + path.sep)) throw new Error("The activity file is outside the history folder.");
  }
  let destination = action === "edit" ? item.path : item.kind === "file" ? path.dirname(item.path) : item.path;
  if (action === "reveal") {
    while (!fs.existsSync(destination)) {
      const parent = path.dirname(destination);
      if (parent === destination) throw new Error("This storage folder is not available.");
      destination = parent;
    }
  }
  const platform = process.platform;
  const command = platform === "win32" ? (action === "edit" ? "notepad.exe" : "explorer.exe") : platform === "darwin" ? "open" : "xdg-open";
  const args = platform === "darwin" && action === "edit" ? ["-t", destination] : [destination];
  await new Promise<void>((resolve, reject) => {
    // This is a visible editor or folder window explicitly requested by its button.
    const child = spawn(command, args, { shell: false, stdio: "ignore", detached: true, windowsHide: false });
    child.once("error", reject);
    child.once("spawn", () => { child.unref(); resolve(); });
  });
}
